[project]
name = "arroyo"
version = "0.0.1"
authors = [
    { name="Dylan McReynolds", email="dmcreynolds@lbl.gov"},
]
description = "a library for processing streams of data"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "python-dotenv",
    "pandas",
    "numpy",
    "pydantic>=2.0",
    "typer",
]

[project.optional-dependencies]
# These are required for developing the package (running the tests, building
# the documentation) but not necessarily required for _using_ it.
dev = [
    "fakeredis",
    "flake8",
    "pre-commit",
    "pyzmq",
    "redis",
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "tiled[server]",
    "fakeredis"
]

zmq = [
    "pyzmq"
]

redis = [
    "redis"
]

[project.urls]
Homepage = "https://github.com/als-computing/als_arroyo"
Issues = "https://github.com/als-computing/als_arroyo/issues"


[tool.isort]
profile = "black"
