name: Run Tests with Pixi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
      name: Static Code Checks
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'
      - uses: pre-commit/action@v3.0.0
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Use a version compatible with your project

      # Step 3: Install Pixi
      - name: Install Pixi
        run: |
          python -m pip install --upgrade pip
          pip install pixi

      # Step 4: Install project dependencies with Pixi
      - name: Install dependencies with Pixi
        run: |
          pixi migrate
          pixi install
          pixi install --dev

      # Step 5: Run tests
      - name: Run tests
        run: |
          pixi run pytest

      # Step 6: Cache dependencies for future runs for faster execution
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
